### ISSUE TITLE
Does Chemalot_knime works general-purpose knime workflows?

### ISSUE THREAD

**Issue by ajason08** [chemalot/chemalot_knime#3]
I am more interesting in machine learning and natural language processing,
can I use this extension to develop command_line-based Knime workflows for my custom applications?
I read this extension allows to create programs via instantiation of Knime's nodes "for processing chemical compounds", but is it limited to those kind of nodes?
Thank you, this is a very interesting project.

**Comment by bgobbi** [comment]
The data is exchanged as an SDF file which is a chemical data exchange format.

It would probably not be too difficult to extend the code to use a tab separated files as an alternative data exchange format but I will not have time to implement this in the near future.
